hw10_project/hw10_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('users/', include("users.urls")),

]

hw10_project/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name ="root"),
    path("<int:page>", views.main, name ="root_paginate"),
    path('author/<str:author_id>', views.author_about, name='author'),
    path('tag/<str:tag_name>/', views.tag_page, name='tag_page'),
    path('author_for_tag/<int:author_id>', views.author_for_tag, name='author_for_tag'),
    path('top-tags/', views.render_tags, name='top_tags'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_tag/', views.add_tag, name='add_tag'),
]

hw10_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from . import views
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path('signup/', views.RegisterView.as_view(), name='signup'),
    path('signin/',
         LoginView.as_view(template_name='users/login.html', form_class=LoginForm,
                           redirect_authenticated_user=True), name='signin'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw10_project/quotes/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    tags = models.ManyToManyField(Tag)
    quote = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

hw10_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, SelectMultiple, Select, Textarea, \
    ChoiceField, ModelChoiceField

from .models import Tag, Author, Quote


class AuthorForm(ModelForm):
    fullname = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    born_date = CharField(max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))
    born_location = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    description = CharField(required=True, widget=Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Tag
        fields = ['name']
        exclude = ['tags']


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=TextInput(attrs={"class": "form-control"}))
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'),
                                    widget=SelectMultiple(attrs={"class": "form-select", "size": "7"}))
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'))

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

hw10_project/quotes/views.py
from django.shortcuts import render, redirect
from django.db.models import Count
from django.db import connection
from django.core.paginator import Paginator

from .utils import get_mongodb
from bson.objectid import ObjectId
from .models import Quote, Tag, Author
from .forms import QuoteForm, AuthorForm, TagForm
from django.contrib.auth.decorators import login_required


def main(request, page=1, num_tags=10):
    db = get_mongodb()
    # db = connection.cursor()
    # print(db)
    quotes = db.quotes.find()
    # data = Quote.objects.all().order_by('-created_at')
    # quotes = [quote.__dict__ for quote in data]
    # print(str(quotes), list(quotes))
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:num_tags]
    latest_quote = Quote.objects.latest('created_at')
    tags_for_latest_quote = latest_quote.tags.all()
    author_for_latest_quote = Author.objects.get(id=latest_quote.author_id)
    return render(request, 'quotes/index.html',
                  context={"quotes": quotes_on_page,
                           'tags10': tags,
                           'latest_quote': latest_quote,
                           'author_for_latest_quote': author_for_latest_quote,
                           'tags_for_latest_quote': tags_for_latest_quote})


def author_about(request, author_id, num_tags=10):
    db = get_mongodb()
    author = db.authors.find_one({'_id': ObjectId(author_id)})
    print(author)
    # author = Author.objects.get(id=author_id)
    tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:num_tags]
    return render(request, 'quotes/author.html', context={'author': author, 'tags10': tags})
    tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:num_tags]
    return render(request, 'quotes/author.html', context={'author': author, 'tags10': tags})


def tag_page(request, tag_name, num_tags=10):
    tag = Tag.objects.get(name=tag_name)
    quotes_with_tag = Quote.objects.filter(tags=tag)
    tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:num_tags]
    return render(request, 'quotes/tag.html', {'quotes_with_tag': quotes_with_tag, 'tag': tag, 'tags10': tags})


def render_tags(request, num_tags=10, template_name='quotes/top_tags.html'):
    top_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:num_tags]
    context = {'top_tags': top_tags}
    tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:num_tags]
    return render(request, template_name, context, {'tags10': tags})


def author_for_tag(request, author_id, num_tags=10):
    author = Author.objects.get(id=author_id)
    tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:num_tags]
    return render(request, 'quotes/author_for_tag.html', context={'author': author, 'tags10': tags})


@login_required  # Проверяет, что пользователь авторизован, прежде чем позволить доступ к представлению.
def add_author(request):  # Обработчик запроса для добавления нового автора.
    if request.method == 'POST':  # Проверка метода запроса (POST или GET).
        form = AuthorForm(request.POST)  # Создание формы на основе POST данных.
        if form.is_valid():  # Проверка валидности данных из формы.
            new_author = form.save(commit=False)  # Создание нового автора без сохранения в БД.
            new_author.user = request.user  # Установка пользователя как создателя автора.
            new_author.save()  # Сохранение автора в БД.
            return redirect(to='quotes:root')  # Перенаправление на главную страницу.
        else:
            return render(request, 'quotes/add_author.html',
                          context={'form': form})  # Отображение формы с ошибками валидации.
    return render(request, 'quotes/add_author.html',
                  context={'form': AuthorForm()})  # Отображение пустой формы для ввода.


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user
            # Получаем объект Author из формы
            author_name = form.cleaned_data["author"]
            author = Author.objects.get(fullname=author_name)
            new_quote.author = author  # Присваиваем объект Author цитате
            new_quote.save()
            form.save_m2m()  # Сохраняем ManyToManyField (теги)
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_quote.html', context={'form': form})
    return render(request, 'quotes/add_quote.html', context={'form': QuoteForm()})


@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_tag.html', context={'form': form})
    return render(request, 'quotes/add_tag.html', context={'form': TagForm()})

hw10_project/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
<h3>Add Author</h3>

{% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <strong>Oops! Something went wrong:</strong>
        <ul>
        {% for field in form %}
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        {% endfor %}
        </ul>
    </div>
{% endif %}

<form action="{% url 'quotes:add_author' %}" method="post">
    {% csrf_token %}
    <div class="mb-1">
        <label class="form-label">Fullname</label>
        {{form.fullname}}
    </div>

    <div class="mb-1">
        <label class="form-label">Date of Birth</label>
        {{form.born_date}}
    </div>

    <div class="mb-1">
        <label class="form-label">Place of Birth</label>
        {{form.born_location}}
    </div>

   <div class="mb-3">
        <label class="form-label">Description</label>
       {{form.description}}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

hw10_project/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<h3>Add Quote</h3>
<form action="{% url 'quotes:add_quote' %}" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Quote</label>
        {{form.quote}}
    </div>

    <div class="mb-3">
        <label class="form-label">Author</label>
        {{form.author}}
    </div>

    <div class="mb-3">
        <label class="form-label">Tags</label>
        {{form.tags}}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %} 

hw10_project/quotes/templates/quotes/add_tag.html
{% extends "quotes/base.html" %}

{% block content %}
<h3>Add Tag</h3>
<form action="{% url 'quotes:add_tag' %}" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Tag</label>
        {{form.name}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

hw10_project/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> 
        <span class="author-born-date">{{ author.born_date }}</span> 
        <span class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>
{% endblock %}

{% block tags %}
    {% for tag in tags10 %}
        <span class="tag-item">
            <a class="tag" href="/tag/{{ tag.name }}/">{{ tag.name }}</a>
        </span>
    {% endfor %}
{% endblock %}

hw10_project/quotes/templates/quotes/author_for_tag.html
{% extends 'quotes/base.html' %} {% block content %}
<div>
  <h3 class="author-title">{{ author.fullname }}</h3>
  <p>
    <strong>Born:</strong>
    <span class="author-born-date">{{ author.born_date }}</span>
    <span class="author-born-location">{{ author.born_location }}</span>
  </p>
  <p><strong>Description:</strong></p>
  <div class="author-description">{{ author.description }}</div>
</div>
{% endblock %} {% block tags %} {% for tag in tags10 %}
<span class="tag-item">
    <a class="tag" href="/tag/{{ tag.name }}/">{{ tag.name }}</a>
</span>
{% endfor %} {% endblock %}

hw10_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Lovely Quotes</title>
    {% load static %}
    <link
            href="{% static 'quotes/bear.webp' %}"
            rel="shortcut icon"
            type="image/x-icon"
    />
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
            crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}"/>
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"
    ></script>
</head>
<body>
<div class="container pt-3">
    <div class="row header-box">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <div class="cont menu-btn-wrap">
                {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_author' %}" class="btn btn-primary mr-4 tag tag_a">Add Author</a>
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary mr-4 tag tag_a">Add Quote</a>
                <a href="{% url 'quotes:add_tag' %}" class="btn btn-primary mr-4 tag tag_a">Add Tag</a>
                <form id="logout-form" action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary tag tag_a" id="logout-button">Logout</button>
                </form>
                {% else %}
                <a href="{% url 'users:signup' %}" class="btn btn-primary mr-4 tag tag_a">SignUp</a>
                <a href="{% url 'users:signin' %}" class="btn btn-primary mr-4 tag tag_a">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">{% block content %} {% endblock %}</div>
        <div class="col-md-4 tags-box">
            <h2>Top Ten tags</h2>
            {% block tags %} {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

hw10_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}
<div class="fresh-quote-wrap">
    <h3>Fresh Quote</h3>
    <div class="quote fresh" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text"> {{latest_quote.quote}}</span>
        <span>by <small class="author" itemprop="author">{{author_for_latest_quote.fullname}}</small>
            <a href="/author_for_tag/{{latest_quote.author.id}}">  (about)</a>                 
        </span>
        <div class="tags">
            Tags:
            {% for tag in tags_for_latest_quote %}
            <a class="tag" href="/tag/{{ tag.name }}">{{tag.name}}</a>
            {% endfor %}
        </div>
    </div>
</div>


{% for quote in quotes %}
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
    <span class="text" itemprop="text">{{quote.quote}}</span>
    <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author/{{quote.author}}">(about)</a>
      </span>
    <div class="tags">
        Tags:
        {% for tag in quote.tags %}
        <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
        {% endfor %}
    </div>
</div>
{% endfor %}
<nav>
    <ul class="pager">
        <li class="previous">
            <a class="{% if not quotes.has_previous %} disabled {% endif %}"
               href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                <span aria-hidden="true">←</span> Previous
            </a>
        </li>

        <li class="next">
            <a class="{% if not quotes.has_next %} disabled {% endif %}"
               href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next
                <span aria-hidden="true">→</span></a>
        </li>
    </ul>
</nav>
{% endblock %}

{% block tags %}
{% for tag in tags10 %}
    <span class="tag-item">
            <a class="tag" href="/tag/{{ tag.name }}/">{{ tag.name }}</a>
    </span>
{% endfor %}
{% endblock %}

hw10_project/quotes/templates/quotes/tag.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h3>Viewing tag: {{ tag.name }}</h3>
    {% for quote in quotes_with_tag %}
        <div class="quote">
            <p>{{ quote.quote }}</p>
            <p>by {{ quote.author.fullname }} <a href="/author_for_tag/{{quote.author.id}}">  (about)</a>



            <p>Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{ tag.name }}">{{ tag.name }}</a>

                {% endfor %}
            </p>
        </div>
    {% endfor %}
{% endblock %}

{% block tags %}
    {% for tag in tags10 %}
        <span class="tag-item">
            <a class="tag" href="/tag/{{ tag.name }}/">{{ tag.name }}</a>
        </span>
    {% endfor %}
{% endblock %}

hw10_project/quotes/templates/quotes/top_tags.html
{% extends 'quotes/base.html' %}

{% block tags %}
    <h2>Top Ten tags</h2>
    <ul>
        {% for tag in top_tags %}
            <li><a href="{% url 'quotes:tag_page' tag_name=tag.name %}">{{ tag.name }}</a> ({{ tag.num_quotes }})</li>
        {% endfor %}
    </ul>
{% endblock %}

{% block tags %}   
    {% for tag in tags10 %}
        <span class="tag-item">
            <a class="tag" href="/tag/{{ tag.name }}/">{{ tag.name }}</a>
        </span>
    {% endfor %}
{% endblock %}